### PR TITLE
fix: delete_user() should remove both grouping policies and policies

### PR DESCRIPTION
**Pull request by greenhandatsjtu**
For now, `delete_user()` only removes grouping policies:
https://github.com/casbin/casbin-rs/blob/ef5ef67a9257f5864a568ab4eeaae618ab510603/src/rbac_api.rs#L259-L262
But other versions (Golang, Node, Python, etc.) remove both grouping policies and policies, take Golang version for example:
https://github.com/casbin/casbin/blob/cb944fd5ef0a0029b6e74b8ca658f7dcb72e69f9/rbac_api.go#L95-L104

Previous discussion is here ( https://github.com/casbin/node-casbin/issues/118 ) , and participants including @hsluoyz agreed that `delete_user()` should also delete policies, not only grouping policies.

Related PRs:
+ Golang ver: https://github.com/casbin/casbin/pull/364
+ Node ver: https://github.com/casbin/node-casbin/pull/119

PS: I'm a GSoC 2022 candidate and submitted my proposal for `casbin-rs`. I've made several PRs to Casbin community, this is my first PR to `casbin-rs`, glad to meet all of you!

### CODE REVIEW

**Comment by hsluoyz** [comment]
@PsiACE

**Review by PsiACE — APPROVED** [review]
LGTM

**Comment by greenhandatsjtu** [comment]
Hi @PsiACE , thanks for reviewing! I'm a GSoC 2022 candidate applying for Rust project. I've contributed to several Casbin repos like [casdoor](https://github.com/casdoor/casdoor/pull/729), [casnode](https://github.com/casbin/casnode/pull/502), and [casbin-website](https://github.com/casbin/casbin-website/pull/327), and now I want to make some contributions to `casbin-rs` related repos, could you please give me some advices on what I should work on next? Thank you!
Currently, I'm trying to solve this issue: https://github.com/casbin-rs/sqlx-adapter/issues/64

**Comment by PsiACE** [comment]
> could you please give me some advices on what I should work on next? 

It is good to see that you have chosen Casbin Rust in GSoC 2022. At this stage, we encourage students to get involved in the maintenance of Casbin Rust and its surrounding ecology. 

If you have any questions, you can also contact me by email.

**Review by hackerchai — APPROVED** [review]
LGTM

**Pull request merged**
