### PR TITLE
ci: add BENCHMARK_TOKEN

### PR DESCRIPTION
**Pull request by smrpn**
Signed-off-by: smrpn <samarpan_d@pp.iitr.ac.in>

### CODE REVIEW

**Comment by PsiACE** [comment]
Doesn’t seem to trigger the benchmark, would you mind trying [this config](https://github.com/boa-dev/boa/blob/master/.github/workflows/pull_request.yml)?

**Comment by smrpn** [comment]
> Doesn’t seem to trigger the benchmark, would you mind trying [this config](https://github.com/boa-dev/boa/blob/master/.github/workflows/pull_request.yml)?

I'm doing that

**Comment by smrpn** [comment]
@PsiACE I changed to the master branch for the action. It has this error - 
Screenshot from 2021-05-25 07-49-11
https://github.com/smrpn/casbin-rs/pull/6/checks?check_run_id=2661076819

**Comment by PsiACE** [comment]
@smrpn I don’t know exactly what happened, but maybe we can try to remove some useless `JSON.stringify()`

**Pull request closed without merging**
