### PR TITLE
Improve/add function and remove gg2 gg3

### PR DESCRIPTION
**Pull request by GopherJ**
This PR does four things

1. improves the `in` operaor part, before it matches only `sub`, `obj` etc. Now it matches also `tenant` (all the things come after `r.` and `p.`)
2. convert `g(r.sub, p.sub)` to `g([r.sub, p.sub])` so that we can remove `gg2` `gg3` function
3. add `add_function` method to `enforcer`
4. fix part of visibility problems on `model` and `enforcer`

### CODE REVIEW

**Comment by GopherJ** [comment]
Hello @hsluoyz @xcaptain could you review it ?

**Comment by hsluoyz** [comment]
Hi @GopherJ can we remove this merge commit?

image

**Comment by GopherJ** [comment]
hello @hsluoyz it's more because that `origin/master` merged a new PR and I did the changes before that.

how about now? I should have only 4 commits

**Comment by hsluoyz** [comment]
@GopherJ merged. BTW, do you have any comments on this? https://github.com/casbin/casbin-rs/issues/5#issuecomment-572869288

**Pull request merged**
