### PR TITLE
make enforce immutable and add enforce_mut

### PR DESCRIPTION
**Pull request by GopherJ**

### CODE REVIEW

**Comment by hsluoyz** [comment]
@nodece @xcaptain

**Comment by GopherJ** [comment]
@xcaptain I have some doubt actually because I'm afraid that users don't use `enforce_mut` or they didn't notice that `enforce_mut` is necessary for cachedEnforcer, I'll need to write this somewhere

**Comment by xcaptain** [comment]
@GopherJ You can continue optimizing `CachedEnforcer`, but don't affect `Enforcer` is used more frequently :smile:  Maybe you can remove `enforce_mut` method in `CachedEnforcer`

**Comment by GopherJ** [comment]
@xcaptain  If this can be solved: https://github.com/rust-lang/rust/issues/72078, I can then solve this issue, no need for `enforce_mut`

**Pull request merged**
