### PR TITLE
fix: possible endless loop when passing /{} or /:/ to keyMatch2 and 3

### LINKED ISSUE #282: keyMatch2 and keyMatch3 can loop indefinitely
The loop in keyMatch2 and keyMatch3 can spin forever when encountering a `/{}` or a `/:`. The go implementation does not seem to have this problem.

Instead of loop forever, either this should panic or not match anything.

We can provide a MR when someone decided how this should be fixed.

### PR DESCRIPTION
**Pull request by valkum**
The go implementation uses a replace_all instead of this loop which
avoids the possible endless loop. This PR changes the implementation of keyMatch2 and keyMatch3 to the one similar to the go implementation.

A benchmark with a single parameter `/foo/{bar}/foo` showed no meaningful impact. 15.09 ns to 15.1 ns per iteration.

## Changes

`/{}` will no be replaced by `/[^/]+` (`/:` accordingly), basically using them as unnamed url parts.
Thus `/{}/bar` will now match `/foo/bar`

Fixes #282

### CODE REVIEW

**Comment by PsiACE** [comment]
hi @valkum , pls make clippy happy. ty!

**Comment by hsluoyz** [comment]
@valkum plz fix:

image

image

**Comment by PsiACE** [comment]
> Clippy is not happy because of some different deprecation warning of rhai. I guess that should be fixed in its own pull request.

You are right, I will be doing a fix later, probably tomorrow.

**Review by PsiACE — APPROVED** [review]
LGTM, Ty!

**Review by hackerchai — APPROVED** [review]
LGTM! waiting for fix the clippy

**Pull request merged**
