### PR TITLE
Create release.yml

### PR DESCRIPTION
**Pull request by PsiACE**
Try to release & publish automatically.

Reference: 
- https://github.com/seunlanlege/arc-reactor/blob/master/.github/workflows/main.yml
- https://github.com/actions/create-release/#example-workflow---create-a-release

Status: **Pass**.

Usage: Add `CARGO_TOKEN` to `secrets`.

Expects:
- Publish to crates.io
- Create release on GitHub.

Close: #58

### CODE REVIEW

**Comment by PsiACE** [comment]
Not sure if it works correctly, because I don't have anything to publish right now.

But based on the work of others, it seems to be expected.

**Comment by PsiACE** [comment]
@hsluoyz @GopherJ Please check it.

Test in a boring little [demo for argh](https://github.com/PsiACE/argh-demo/), 
View the running results https://github.com/PsiACE/argh-demo/runs/466937360

For successful use:
- add `CARGO_TOKEN` to `secrets`.
- run `cargo publish --dry-run` locally and pass
- `git tag v*` && `git push origin v*`, `v*` means `v0.1.1`/`v1.2.3` etc.

**Comment by GopherJ** [comment]
@PsiACE Thanks for having made it, I'll check once got time.

For `CARGO_TOKEN`, we'd better have a casbin-rs org token because I don't want to put my personal token there. 

I'll check if the token can be read on github, if not, I can use my personal `CARGO_TOKEN`, if yes, we then need an org account and an org token.

**Comment by GopherJ** [comment]
Currently we are using my personal secret, but since it's not readable, it's ok.

**Pull request merged**
