### PR TITLE
Add some keywords and readme and also optimize --release compiles

### PR DESCRIPTION
**Pull request by omid**
Add some keywords and readme and also optimize --release compiles

### CODE REVIEW

**Comment by hsluoyz** [comment]
lgtm. @GopherJ @xcaptain can you reivew it?

**Comment by GopherJ** [comment]
Hello @omid thanks for your contributions. keywords look good to me. Can I know what opt-level=0 is for?  
Normally the release profile is opt-level=3.

**Comment by omid** [comment]
Hey,

You can read it here:
https://doc.rust-lang.org/1.41.0/cargo/reference/profiles.html#overrides

And can follow the discussion here about it:
https://twitter.com/CryZe107/status/1222947784103538689

**Comment by GopherJ** [comment]
lgtm @omid thanks for your links

**Pull request merged**
