### PR TITLE
Change enforce and enforce_mut to non-async.

### PR DESCRIPTION
**Pull request by schungx**

### CODE REVIEW

**Comment by schungx** [comment]
OK, this is it.  It looks like it is still PR-ing a godzillion previous commits, but they all seem to match out with the existing files, so the net effect are the right changes.

**Comment by GopherJ** [comment]
yes you started from schungx/master then certainly it will contain all the previous commits

**Comment by GopherJ** [comment]
you can actually reset hard to a casbin commit then pull master on it finally use github cherry-pick and force push

**Comment by GopherJ** [comment]
For example you can do:

```
git reset --hard <commit hash just before 9669dae>
git remote add casbin https://github.com/casbin/casbin-rs
git fetch casbin
git rebase casbin/master
git cherry-pick 9ffc1e0 -n
```

**Comment by schungx** [comment]
Hey it worked!
;-D

**Comment by GopherJ** [comment]
hi @schungx 
could you do
```
git remote add GopherJ https://github.com/GopherJ/casbin-rs
git fetch GopherJ
git rebase -X theirs GopherJ/sync-enforce
```
I fixed CI their and added some tiny changes

**Comment by schungx** [comment]
OK... I can't push to my own repo:

```
 ! [remote rejected] master -> master (refusing to allow an OAuth App to create or update workflow `.github/workflows/ci.yml` without `workflow` scope)
```

Do I just skip that file or something?

**Comment by schungx** [comment]
OK, had to go thru some hoops to push `ci.yaml` into my repo, but done.

**Comment by schungx** [comment]
However, pulling in your repo makes is such that I can no longer build on Windows.

```
TARGET = Some("x86_64-pc-windows-gnu")
OPT_LEVEL = Some("0")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
running: "gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "C:\\Git\\casbin-rs\\target\\debug\\build\\wepoll-sys-2ce793a69d7eefdb\\out\\wepoll-build" "-Wall" "-Wextra" "-o" "C:\\Git\\casbin-rs\\target\\debug\\build\\wepoll-sys-2ce793a69d7eefdb\\out\\wepoll-build\\wepoll.o" "-c" "C:\\Git\\casbin-rs\\target\\debug\\build\\wepoll-sys-2ce793a69d7eefdb\\out\\wepoll-build\\wepoll.c"
```

Got stuck on `wepoll-sys`.

**Comment by GopherJ** [comment]
emm...that's because I upgraded async-std to 1.6.0 maybe, now it uses smol as runtime and dont depend on mio anymore.

But normally it should compile on windows, have you tried `cargo clean && cargo check`?

**Comment by schungx** [comment]
> cargo clean && cargo check

Yes I did, and `cargo check` died at the exact same spot...

**Comment by GopherJ** [comment]
ok I'll try to fix it

**Comment by schungx** [comment]
Turns out that I probably need to find a pre-built `wepoll` for Windows somewhere unless I want to compile it  myself...

**Pull request merged**
