### PR TITLE
feat: switch to ritelinked and provide amortized feature

### PR DESCRIPTION
**Pull request by PsiACE**
In this PR, I use my crate `ritelinked` to replace `indexmap`. In the local test, it will bring a big performance improvement for most benchmarks. Of course, this still needs to be further evaluated.

In addition, a new `amortized` feature is provided. Thanks to `griddle` , although it will slow down the performance, but there is reason to believe that it can reduce the long tail effect.

Signed-off-by: Chojan Shang <psiace@outlook.com>

### CODE REVIEW

**Comment by GopherJ** [comment]
@PsiACE could you fix CI

**Comment by PsiACE** [comment]
> @PsiACE could you fix CI

I need to see how to solve this problem, because the `explain` feature uses APIs that are not currently supported by `ritelinked` .

**Comment by PsiACE** [comment]
Approximately 2% performance improvement.

Sometimes we may see exaggerated data (whether it is improvement or regression), which may be caused by random data.

**Comment by hackerchai** [comment]
lgtm

**Review by hackerchai — COMMENTED** [review]
lgtm

**Comment by PsiACE** [comment]
ping @GopherJ what do you think about this?

**Comment by GopherJ** [comment]
@PsiACE I think it's pretty good but 2% in github actions isn't big as well, is ritelinked already 1.0?

**Review by GopherJ — APPROVED** [review]

**Comment by PsiACE** [comment]
> @PsiACE I think it's pretty good but 2% in github actions isn't big as well, if it arrives at 5% it'll be super cool, also is ritelinked already 1.0 OR do you consider it super stable now? because in authorization library we may need good stability

I think it can be regarded as a stable crate. although version 1.0 is not currently released. Also, even if the next version of indexmap is released, ritelinked still has performance advantages in our benchmark.

**Comment by GopherJ** [comment]
ok thanks for your effort!

**Pull request merged**
