### PR TITLE
Refactor: modify Vec<&str> to Vec<String> (#73)

### PR DESCRIPTION
**Pull request by hackerchai**
fix issue#73

Use Vec<String> instead of Vec<&str> to avoid lifetime issue

### CODE REVIEW

**Comment by xcaptain** [comment]
@hackerchai We don't need to change `&str` to `String`. https://hermanradtke.com/2015/05/03/string-vs-str-in-rust-functions.html
图片

**Comment by GopherJ** [comment]
Hello @xcaptain, this is a good post which explains why String is better than &str in some situations.

https://github.com/projectfluent/fluent-rs/issues/123

Using &str in casbin-rs is not realistic, although it may be more efficient.

Image that a client generated a Vec<String> as policies, and he wants to use in casbin-rs, he has to converted Vec<String> to Vec<&str>. That's not convenient.

In realworld example, we always get `Vec<String>` from file system, network etc. We often just generate `Vec<String>` over `Vec<&str>`

**Comment by GopherJ** [comment]
An example of code is the following which I encountered in my personal project:

```rust
fn load_records<P: AsRef<Path>>(p: P) -> Vec<StringRecord> {
    if let Ok(mut rdr) = ReaderBuilder::new()
        .has_headers(false)
        .double_quote(false)
        .comment(Some(b'#'))
        .delimiter(b',')
        .trim(Trim::All)
        .from_path(p)
    {
        if let Ok(records) = rdr.records().collect::<Result<Vec<StringRecord>, Error>>() {
            return records
                .into_iter()
                .filter(|r| is_valid_policy(r) || is_valid_grouping_policy(r))
                .collect::<Vec<StringRecord>>();
        }
    }

    vec![]
}
```

**Comment by xcaptain** [comment]
Ok, I agree to use owned string in all the public APIs.

**Comment by GopherJ** [comment]
Thanks @xcaptain and glad to see you agree with me!

**Comment by xcaptain** [comment]
Found a RFC here https://github.com/rust-lang/rfcs/blob/master/text/0241-deref-conversions.md

After it get implemented we don't need to worry whether use String or &str anymore, the compiler can help us.

**Comment by DevinR528** [comment]
I'm pretty sure [auto-deref](https://github.com/rust-lang/rfcs/pull/241) is implemented I think what it allows is
```rust
fn use_vector<T>(vec: &[T]) {}
fn use_string(s: &str) {}

let v = vec![0, 1, 2];
let s = String::new();

vector(&v);
use_string(&s);
```

**Comment by xcaptain** [comment]
@DevinR528 You are right, my mistake, RFC 241 has been merged.

I was think to write a function that can take `String` and `&str` at the same time. The deref trait makes `&String` equals to `&str` but not very idea.

How about we use `AsRef` https://doc.rust-lang.org/std/convert/trait.AsRef.html here, then we don't need to dereference a string manually?

**Comment by GopherJ** [comment]
@xcaptain   I think `Into<String> + Send + Sync` can help

**Comment by DevinR528** [comment]
@GopherJ as you know (you also tried to get the Api traits to take an `Into<String>`) it is way more trouble than it would be worth. I'm pretty sure to get any of the traits to use `Into<String>` we would have to `Box` it since its a `dyn Into<string>` and not boxing we may run into the same problem as with
```rust
pub struct Enforcer<A: Adaptor> {
    adaptor: A
```
where it only accepts one instance.

**Comment by GopherJ** [comment]
@DevinR528 Yes I agree, I removed static dispatcher because it causes some constraints.

> We'll not be able to change types in runtime. (once instance is generated)

Anyway I think we should stick to `Vec<String>` before finding better solution

**Comment by GopherJ** [comment]
I think we can merge this.

**Pull request merged**
