### PR TITLE
add error handling

### PR DESCRIPTION
**Pull request by xcaptain**
`Adapter` is easy to generate error, because of error propagating, `model` and `enforcer` that used those adapter methods must return an error.

I actually don't like this commit because of those annoying `Results`, what do you think? @GopherJ @hsluoyz

### CODE REVIEW

**Comment by hsluoyz** [comment]
Please refer to Golang Casbin v2.x about error handling.

**Comment by xcaptain** [comment]
@hsluoyz  Sorry I didn't express correctly, it's not `model` uses `adapter` but `adapter` uses `model`, so errors in `adapter` don't propagate to `model`. But `enforcer` uses `adapter`, like `load_policy`, `add_role_for_user` ..., so these methods should return `Result`.

After adding a custom `Result` to `adapter`, adapters and enforce apis changed simultaneously.

**Comment by xcaptain** [comment]
I can add more error test cases later, but we can discuss whether we should change method definitions in `Adapter`

**Comment by hsluoyz** [comment]
Keeping the same with Golang Casbin would be OK.

**Pull request merged**
