### PR TITLE
add enforce_with_matcher && make it possible to use p1..n in matcher && supports multiple matchers

### PR DESCRIPTION
**Pull request by GopherJ**
This PR allows to use model like this:

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub_rule, obj, act
p1 = sub_rule, obj, act
p2 = sub_rule, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = !eval(p.sub_rule) && r.obj == p.obj && r.act == p.act
m1 = eval(p1.sub_rule) && r.obj == p1.obj && r.act == p1.act
m2 = m && m1 && eval(p2.sub_rule) && r.obj == p2.obj && r.act == p2.act
```

then if we have the following policies:
```
// only m is using p, but we have ! before eval, so it's turning to
// only when one person's age <= 60, he/she will be able to read /ata1

p, r.sub.age > 60, /data1, read

// only m1 is using p1, if we use m1 for enforcing
// it allows people with age > 16 to read /data1

p1, r.sub.age > 16, /data1, read

// only m2 is using p2, if we use m2 for enforcing
// it allows people with age > 50 && <= 60 to read /data1
// why do we have <= 60 here ?
// because m && m1 means age <= 60 && age > 16
// plus the following policy
// it turns to age > 50 && age <= 60

p2, r.sub.age > 50, /data1, read
```

```rust
// authorized because 16 <= 60
e.enforce_with_matcher(&[r#"{"name": "alice", "age": 16}"#, "/data1", "read"], "m")

// denied because 70 > 60
e.enforce_with_matcher(&[r#"{"name": "alice", "age": 70}"#, "/data1", "read"], "m")

// authorized because 19 > 16
e.enforce_with_matcher(&[r#"{"name": "bob", "age": 19}"#, "/data1", "read"], "m1")

// denied because 15 < 16
e.enforce_with_matcher(&[r#"{"name": "bob", "age": 15}"#, "/data1", "read"], "m1")

// authorized because m && m1 means >16 && <= 60, plus p2
// it means > 50 && <= 60
e.enforce_with_matcher(&[r#"{"name": "bob", "age": 51}"#, "/data1", "read"], "m2")

// denied because 61 > 60
e.enforce_with_matcher(&[r#"{"name": "bob", "age": 61}"#, "/data1", "read"], "m2")
```

Here we will iterate all matchers, and extract `ptype` from them, then calculate **m**, **m1**, **m2** by order (**we will need hashmap which can keep iterate orders.**)

### CODE REVIEW

**Comment by hsluoyz** [comment]
How to merge `m, m1, m2` into a single boolean result?

**Comment by GopherJ** [comment]
@hsluoyz It's also expression evaluation, so basically we extract the value of **m** and then extract the value of **m1** and the run again the policy loop for `p2`

**Comment by GopherJ** [comment]
But now, **e1**, **e2**, **e3**... **r1**, **r2**, **r3**..  is not supported yet. I dont have a good idea.

**Comment by hsluoyz** [comment]
IIRC, teaclave is using multiple matchers. How do they use? If possible, we can keep close to their logic and then we can replace its mechanism one day.

**Comment by GopherJ** [comment]
@hsluoyz  I'm not sure because I didn't take time to check their implementation. Their scenario is much more smaller I think because it's only for making a product for their usecase.

**Comment by GopherJ** [comment]
bench diff:

```
 name                                         before ns/iter  after ns/iter  diff ns/iter  diff %  speedup 

 b_benchmark_abac_model                       7,394           7,229                  -165  -2.23%   x 1.02 

 b_benchmark_basic_model                      12,376          13,529                1,153   9.32%   x 0.91 

 b_benchmark_cached_abac_model                460             640                     180  39.13%   x 0.72 

 b_benchmark_cached_key_match                 463             649                     186  40.17%   x 0.71 

 b_benchmark_cached_priority_model            458             631                     173  37.77%   x 0.73 

 b_benchmark_cached_rbac_model                456             658                     202  44.30%   x 0.69 

 b_benchmark_cached_rbac_model_large          457             628                     171  37.42%   x 0.73 

 b_benchmark_cached_rbac_model_medium         458             620                     162  35.37%   x 0.74 

 b_benchmark_cached_rbac_model_small          461             648                     187  40.56%   x 0.71 

 b_benchmark_cached_rbac_model_with_domains   519             704                     185  35.65%   x 0.74 

 b_benchmark_cached_rbac_with_deny            463             661                     198  42.76%   x 0.70 

 b_benchmark_cached_rbac_with_resource_roles  456             643                     187  41.01%   x 0.71 

 b_benchmark_key_match                        68,123          77,794                9,671  14.20%   x 0.88 

 b_benchmark_priority_model                   11,152          10,585                 -567  -5.08%   x 1.05 

 b_benchmark_raw                              6               6                         0   0.00%   x 1.00 

 b_benchmark_rbac_model                       29,704          30,694                  990   3.33%   x 0.97 

 b_benchmark_rbac_model_large                 68,581,740      67,583,930         -997,810  -1.45%   x 1.01 

 b_benchmark_rbac_model_medium                6,466,802       6,465,010            -1,792  -0.03%   x 1.00 

 b_benchmark_rbac_model_small                 632,894         618,416             -14,478  -2.29%   x 1.02 

 b_benchmark_rbac_model_with_domains          42,408          44,336                1,928   4.55%   x 0.96 

 b_benchmark_rbac_with_deny                   38,431          37,969                 -462  -1.20%   x 1.01 

 b_benchmark_rbac_with_resource_roles         26,388          27,359                  971   3.68%   x 0.96 

 b_benmark_cached_basic_model                 460             613                     153  33.26%   x 0.75
```

**Comment by GopherJ** [comment]
Another question is how to use specific `effect` for matcher or matchers.

One option is:

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub_rule, obj, act
p1 = sub_rule, obj, act
p2 = sub_rule, obj, act

[policy_effect]
e = some(where (p.eft == allow))
e1 = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers.e]
m = !eval(p.sub_rule) && r.obj == p.obj && r.act == p.act
m1 = eval(p1.sub_rule) && r.obj == p1.obj && r.act == p1.act

[matchers.e1]
m2 = m && m1 && eval(p2.sub_rule) && r.obj == p2.obj && r.act == p2.act

```

**Comment by GopherJ** [comment]
@hsluoyz Do you have some advice?

**Comment by hsluoyz** [comment]
I'm still not clear about the goal. Why we add multiple matchers, effects, etc. ? Why can't user use multiple enforcers?

**Comment by GopherJ** [comment]
@hsluoyz 

How do we solve the problem of synchronization if we use multiple enforcers?

Say that we have two enforcers with different matchers, they share the same piece of data but designed to different purpose.

If one policy has been added to one of the two enforcers, we should see the effect on another.
In this case, users will need to use watcher, but watcher is buggy for this moment.

**Comment by GopherJ** [comment]
@hsluoyz  Another thing is: now only `p` works, `p2` `p3` `p4`... dont work basically, we should make them work right?

**Comment by GopherJ** [comment]
One concrete example is:

I would like  to use casbin to protect one application, and this application has UI and backend

**Comment by GopherJ** [comment]
The latest PR will not calculate all by default, if one matcher doesn't rely on the other we just calculate for it.

**Comment by GopherJ** [comment]
Now we support multiple matchers + multiple effects. I didn't implement an more complex effect, now `m[n]` will use `e[n]`.

so something like this will be valid
```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub_rule, obj, act
p1 = sub_rule, obj, act
p2 = sub_rule, obj, act

[policy_effect]
e = some(where (p.eft == allow))
e1 = some(where (p.eft == allow))
e2 = some(where (p.eft == allow))

[matchers]
m = !eval(p.sub_rule) && r.obj == p.obj && r.act == p.act
m1 = eval(p1.sub_rule) && r.obj == p1.obj && r.act == p1.act
m2 = m && m1 && eval(p2.sub_rule) && r.obj == p2.obj && r.act == p2.act
```

**Comment by GopherJ** [comment]
@hsluoyz could you have a look to see what can we improve?

**Comment by GopherJ** [comment]
Certainly we will have a bench downgrade as shown in CI:

```
 name                                         before ns/iter  after ns/iter  diff ns/iter  diff %  speedup 

 b_benchmark_abac_model                       7,838           7,793                   -45  -0.57%   x 1.01 

 b_benchmark_basic_model                      12,473          14,199                1,726  13.84%   x 0.88 

 b_benchmark_cached_abac_model                463             639                     176  38.01%   x 0.72 

 b_benchmark_cached_key_match                 479             649                     170  35.49%   x 0.74 

 b_benchmark_cached_priority_model            471             628                     157  33.33%   x 0.75 

 b_benchmark_cached_rbac_model                464             647                     183  39.44%   x 0.72 

 b_benchmark_cached_rbac_model_large          457             655                     198  43.33%   x 0.70 

 b_benchmark_cached_rbac_model_medium         459             658                     199  43.36%   x 0.70 

 b_benchmark_cached_rbac_model_small          471             657                     186  39.49%   x 0.72 

 b_benchmark_cached_rbac_model_with_domains   526             708                     182  34.60%   x 0.74 

 b_benchmark_cached_rbac_with_deny            467             634                     167  35.76%   x 0.74 

 b_benchmark_cached_rbac_with_resource_roles  473             651                     178  37.63%   x 0.73 

 b_benchmark_key_match                        70,199          83,255               13,056  18.60%   x 0.84 

 b_benchmark_priority_model                   11,284          11,729                  445   3.94%   x 0.96 

 b_benchmark_raw                              6               6                         0   0.00%   x 1.00 

 b_benchmark_rbac_model                       30,442          32,173                1,731   5.69%   x 0.95 

 b_benchmark_rbac_model_large                 67,699,313      66,577,640       -1,121,673  -1.66%   x 1.02 

 b_benchmark_rbac_model_medium                6,460,497       6,373,585           -86,912  -1.35%   x 1.01 

 b_benchmark_rbac_model_small                 641,921         623,593             -18,328  -2.86%   x 1.03 

 b_benchmark_rbac_model_with_domains          43,212          44,235                1,023   2.37%   x 0.98 

 b_benchmark_rbac_with_deny                   37,737          38,848                1,111   2.94%   x 0.97 

 b_benchmark_rbac_with_resource_roles         26,335          28,055                1,720   6.53%   x 0.94 

 b_benmark_cached_basic_model                 462             623                     161  34.85%   x 0.74 
```

**Pull request closed without merging**
