### PR TITLE
objekt-clonable crate imported to remove clone_box

### PR DESCRIPTION
**Pull request by DevinR528**
I just commented out the parts that could be removed and added an idea to a todo I may work on if you think that'd be ok. I'll try the Rc as well but like I said it may not be worth changing.

### CODE REVIEW

**Comment by xcaptain** [comment]
So you're just using objectet to do the clone? I thought you were to do some thing like

```rust
pub struct Enforcer<A: Adapter, R: RoleManager> {
    pub model: Model,
    pub adapter: A,
    pub fm: FunctionMap,
    pub eft: Box<dyn Effector>,
    pub rm: R,
    pub auto_save: bool,
    auto_build_role_links: bool,
}
```

**Comment by xcaptain** [comment]
I made a simple work around at https://github.com/casbin/casbin-rs/pull/22/commits/857ee91ef216cecbf4142db819ce6094558b3be1 to make `g function` support 2 or 3 parameters. I don't think it's the elegant way, do you have any good idea?

Do you have any idea on how to replace an object at runtime? like replace the `DefaultRoleManager` to another role manager.

**Comment by DevinR528** [comment]
Why is `RoleManager` a trait is there more than `DefaultRoleManager`? If `DefaultRoleManager` is the only kind of role manager using a trait might not make sense, the adapter trait is perfect because you have two types of adapter that share behavior.  

I would make the `MatchFnClone` something like this
```rust
pub trait MatchFnClone: Fn(&str, &str, Option<&str>) -> bool {
    fn clone_box(&self) -> Box<dyn MatchFnClone>;
}

impl<T> MatchFnClone for T
where
    T: 'static + Fn(&str, &str, Option<&str>) -> bool + Clone,
{
    fn clone_box(&self) -> Box<dyn MatchFnClone> {
        Box::new(self.clone())
    }
}
```
I started converting all the String's to &str and the Option but I could not find where the `MatchFnClone` is actually called or where the args are passed into it.

If you could link the line where you want to
> Do you have any idea on how to replace an object at runtime? like replace the DefaultRoleManager to another role manager.
That way I'll have a better idea of what you mean exactly.

**Comment by xcaptain** [comment]
@DevinR528 The `RoleManager` can be replaced in the go version https://github.com/casbin/casbin/blob/master/model_test.go#L341 I have no idea how to achieve the same goal using rust, do you have interest to investigate this?

Also the go version support modifying the `matching_func` at runtime, but our current implementation using `Box<dyn RoleManager>` doesn't allow to modify at runtime, do you have any ideas on this?

图片

**Comment by xcaptain** [comment]
The `g` function is generated at https://github.com/casbin/casbin-rs/blob/master/src/enforcer.rs#L121-L128 I made a small trick that split a g function into `gg2` and `gg3`, gg2 takes 2 parameters and gg3 takes 3. you can take a look at `rbac_model.conf`

```text
[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```
This expression is parsed as
```text
gg2(r_sub, p_sub) && r_obj == p_obj && r_act == p_act
```

In `rbac_with_domains_model.conf`

```text
[matchers]
m = g(r.sub, p.sub, r.dom) && r.dom == p.dom && r.obj == p.obj && r.act == p.act
```
this expression will be parsed as
```text
gg3(r_sub, p_sub, r_dom) && r_dom == p_dom && r_obj == p_obj && r_act == p_act
```

**Pull request closed without merging**
