### PR TITLE
Use immutable strings in Rhai.

### PR DESCRIPTION
**Pull request by schungx**
This PR uses the latest version of Rhai, which uses immutable strings to avoid excessive cloning.

### CODE REVIEW

**Comment by GopherJ** [comment]
@schungx The number seems awesome! Thanks for your work!

image

**Comment by schungx** [comment]
> Could you just fix this error?

Done!

**Comment by GopherJ** [comment]
@schungx I tested in my environment, and there should be average 15%'s bench improvement for large senario

```
 name                                  before ns/iter  after ns/iter  diff ns/iter   diff %  speedup 
 b_benchmark_abac_model                3,962           4,003                    41    1.03%   x 0.99 
 b_benchmark_basic_model               4,443           4,109                  -334   -7.52%   x 1.08 
 b_benchmark_key_match                 16,296          16,624                  328    2.01%   x 0.98 
 b_benchmark_priority_model            4,868           4,934                    66    1.36%   x 0.99 
 b_benchmark_raw                       5               5                         0    0.00%   x 1.00 
 b_benchmark_rbac_model                6,824           6,823                    -1   -0.01%   x 1.00 
 b_benchmark_rbac_model_large          11,633,770      9,562,268        -2,071,502  -17.81%   x 1.22 
 b_benchmark_rbac_model_medium         1,042,977       916,664            -126,313  -12.11%   x 1.14 
 b_benchmark_rbac_model_small          105,794         90,933              -14,861  -14.05%   x 1.16 
 b_benchmark_rbac_model_with_domains   7,142           6,884                  -258   -3.61%   x 1.04 
 b_benchmark_rbac_with_deny            10,859          9,754                -1,105  -10.18%   x 1.11 
 b_benchmark_rbac_with_resource_roles  5,222           4,832                  -390   -7.47%   x 1.08 
 b_benchmark_role_manager_large        2,370,766       2,396,807            26,041    1.10%   x 0.99 
 b_benchmark_role_manager_medium       215,470         216,729               1,259    0.58%   x 0.99 
 b_benchmark_role_manager_small        21,216          21,414                  198    0.93%   x 0.99 
```

**Comment by schungx** [comment]
> I mean these three which heavily rely on rhai's speed

That's expected.  The more string operations it does, the more it saves.  At the cost of introducing an immutable string type, which is wrapped by `Arc`.

For simple models with only a few strings, the additional cost of an atomic reference count may out-weight the benefits of reduced cloning.  The savings really add up when you use the same strings over and over again, such as in matching large number of policies in a tight loop.

However, on my computer I do see significant speed-up in most benchmarks... maybe just because my PC is not very powerful...

**Comment by GopherJ** [comment]
hi @schungx  thanks for making this, since I have also local changes to edit, I edited these manually on my PC, will update soon.

**Pull request closed without merging**
