### PR TITLE
Feat: migrate to Criterion benchmark

### LINKED ISSUE #233: Migrate to Criterion benchmark
https://github.com/bheisler/criterion.rs
More and more rust projects start to use criterion as the default benchark library for more specific performence statistics

### PR DESCRIPTION
**Pull request by smrpn**
Fixes #233 

- [ ] Added github actions support, [criterion-compare-action](https://github.com/boa-dev/criterion-compare-action)

### CODE REVIEW

**Comment by smrpn** [comment]
Please review this @hackerchai @hsluoyz 
There is some problem with the github actions support, which I'm working on. Are there any changes required apart from that?

**Comment by hsluoyz** [comment]
@hackerchai

**Comment by hsluoyz** [comment]
@smrpn plz fix all failed checks:

image

**Comment by smrpn** [comment]
> @smrpn plz fix all failed checks:
> 
> image

on it.

**Pull request closed without merging**
