### PR TITLE
feat: Migrate to Criterion benchmark

### PR DESCRIPTION
**Pull request by smrpn**
- [x] add github actions support for criterion.

### CODE REVIEW

**Comment by smrpn** [comment]
run benchmark is failing because of a deprecated function in the master branch -
```
cargo bench -- --save-baseline master
   Compiling num-traits v0.2.14
   Compiling rhai v0.19.15
   Compiling casbin v2.0.6 (/home/runner/work/casbin-rs/casbin-rs)
warning: unused import: `RegisterFn`
  --> src/enforcer.rs:34:54
   |
34 |     Dynamic, Engine, EvalAltResult, ImmutableString, RegisterFn, Scope,
   |                                                      ^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: use of deprecated trait `rhai::RegisterFn`: this trait is no longer needed and will be removed in the future
  --> src/enforcer.rs:34:54
   |
34 |     Dynamic, Engine, EvalAltResult, ImmutableString, RegisterFn, Scope,
   |                                                      ^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

error[E0599]: no method named `set_fn_1` found for mutable reference `&mut Module` in the current scope
  --> src/enforcer.rs:43:9
   |
43 |     lib.set_fn_1("escape_assertion", |s: ImmutableString| {
   |         ^^^^^^^^ help: there is an associated function with a similar name: `set_fn`

error: aborting due to previous error; 2 warnings emitted
```
The second commit fixes that.

**Comment by smrpn** [comment]
@hackerchai please review this.

**Comment by hsluoyz** [comment]
@smrpn remove merge commits

image

**Comment by hsluoyz** [comment]
@hackerchai

**Comment by hackerchai** [comment]
@smrpn please fix the bench error

**Comment by hsluoyz** [comment]
@smrpn 

image

**Pull request closed without merging**
