### PR TITLE
fix(csv): shouldn't delete double quotes

### PR DESCRIPTION
**Pull request by MATRIXKOO**
use  `double_quotes: Vec<char>` to avoid panic mode

### CODE REVIEW

**Comment by hsluoyz** [comment]
@MATRIXKOO can you fix the CI error?

**Comment by MATRIXKOO** [comment]
Actually, I have no idea to fix the CI error. Because I don't know the thing that leads to those errors.

**Comment by hsluoyz** [comment]
Click to see details, like: https://github.com/casbin/casbin-rs/pull/217/checks?check_run_id=1581711973

image

**Comment by hsluoyz** [comment]
@MATRIXKOO you can also give comments to (and learn from) the PR from one of our senior members, who also authored Casbin-RS: https://github.com/casbin/casbin-rs/pull/216

**Comment by MATRIXKOO** [comment]
It looks like nothing changed ， I have committed a few useless messages. Sorry about that.

**Comment by GopherJ** [comment]
@MATRIXKOO no pb,  thanks for your contribution and let's stick to #216 for now util a better / clean solution being found

**Pull request closed without merging**
