### PR TITLE
Upgrade tokio

### PR DESCRIPTION
**Pull request by hackerchai**

### CODE REVIEW

**Review by PsiACE — APPROVED** [review]

**Comment by hsluoyz** [comment]
@hackerchai the 10 commits look a little messed up, even including 3 merging commits. Can you re-arrange/tidy the commits? Ideally to have 1 or 2 clean commits.

image

**Comment by hackerchai** [comment]
> @hackerchai the 10 commits look a little messed up, even including 3 merging commits. Can you re-arrange/tidy the commits? Ideally to have 1 or 2 clean commits.
> 
> image

@hsluoyz  Sorry for too much commits, the auto-changelog ci seems buggy, I have fixed it. And I see the ci running on MacOS fails, but the ci runs on Ubuntu  is always passd. I think it is a bug for Github Actions, on my macos it passes the build and test. So I suggest to ignore the ci error.

**Comment by hsluoyz** [comment]
@GopherJ

**Comment by hsluoyz** [comment]
@hackerchai plz rebase your PR branch to master HEAD, currently shown two duplicated commits here:

image

**Comment by hackerchai** [comment]
> @hackerchai plz rebase your PR branch to master HEAD, currently shown two duplicated commits here:
> 
> image

@hsluoyz  fixed

**Pull request merged**
