### PR TITLE
Migrate to Criterion benchmark

### LINKED ISSUE #233: Migrate to Criterion benchmark
https://github.com/bheisler/criterion.rs
More and more rust projects start to use criterion as the default benchark library for more specific performence statistics

### PR DESCRIPTION
**Pull request by smrpn**
Fixes #233

### CODE REVIEW

**Comment by hackerchai** [comment]
We also need automatic github actions support, you can refer this [criterion-compare-action](https://github.com/boa-dev/criterion-compare-action).

**Comment by hackerchai** [comment]
@smrpn And please always sign-offf your commits

**Comment by smrpn** [comment]
> We also need automatic github actions support, you can refer this [criterion-compare-action](https://github.com/boa-dev/criterion-compare-action). @smrpn

noted

**Comment by hsluoyz** [comment]
The git history is so messed up. Closed here.

image

**Pull request closed without merging**
