### PR TITLE
feat: replace lru with mini-moka for caching

### PR DESCRIPTION
**Pull request by kbalt**
Replace the `lru` library with `mini-moka` for caching. This allows the API to take `&self` instead of `&mut self` for most operations.

This also allows to only take a read lock when executing `g` functions.

### CODE REVIEW

**Comment by hackerchai** [comment]
@kbalt plz fix the CI errors

**Comment by hsluoyz** [comment]
@kbalt plz fix: https://github.com/casbin/casbin-rs/actions/runs/4699340306/jobs/8332688165?pr=307

image

**Comment by hsluoyz** [comment]
@kbalt plz fix:

image

**Comment by kbalt** [comment]
Code coverage is complaining about a coverage regression in `src/enforcer.rs` when I just added one single line in there. The rest should be resolved now.

**Pull request merged**
