### PR TITLE
Make enforce and enforce_mut non-async.

### PR DESCRIPTION
**Pull request by schungx**

### CODE REVIEW

**Comment by GopherJ** [comment]
Hi could you start from origin/master that will make the commit messages better

**Comment by schungx** [comment]
Not very sure what I need to do...  Just pressed `Create pull request` and it turns out this way...

**Comment by GopherJ** [comment]
Hi @schungx Often I do

```
git remote add origin https://github.com/casbin/casbin-rs
git remote add schungx https://github.com/schungx/casbin-rs
git checkout master
git pull origin master

git checkout -b sync-enforce

// local changes
git push me sync-enforce

// PR
```

**Comment by GopherJ** [comment]
I think in this case you can:

```
git remote add casbin https://github.com/casbin/casbin-rs
git fetch casbin
git checkout casbin/master
git cherry-pick 9ffc1e0 -n
```

**Comment by schungx** [comment]
> @schungx I think in this case you can:

OK... after I've done those, then...?

How do I make a correct PR here?

**Comment by schungx** [comment]
OK.  I'll do the nuclear option.  I'll delete my fork and start again!

**Pull request closed without merging**
