### PR TITLE
Speed improvements

### PR DESCRIPTION
**Pull request by schungx**

### CODE REVIEW

**Comment by schungx** [comment]
OK, this is a new PR.  I assume that's what you need.

**Comment by GopherJ** [comment]
Hi could you fix this clippy error?

image

**Comment by schungx** [comment]
How about getting rid of the lifetime parameter:

```
pub fn escape_eval(m: &str) -> Cow<str> {
    ESC_E.replace_all(m, "eval(escape_assertion(${1}))")
}
```

**Comment by GopherJ** [comment]
let's thanks!

**Pull request merged**
