### PR TITLE
Feat: optimize incremental compilation time

### PR DESCRIPTION
**Pull request by hackerchai**
Signed-off-by: hackerchai <i@hackerchai.com>

### CODE REVIEW

**Comment by hsluoyz** [comment]
@hackerchai plz fix:

image

**Comment by hackerchai** [comment]
@smrpn  Where is the pull request benchmark comment?

**Review by PsiACE — APPROVED** [review]
lgtm, I like rust 1.51.0

**Comment by hackerchai** [comment]
> @hackerchai plz fix:
> 
> image

seems to be random fault of github actions, fixed

**Pull request merged**
