### PR TITLE
 docs: mention that Enforcer is not thread-safe

### LINKED ISSUE #278: Multithreaded environment: RwLock needed around Enforcer with sqlx-adapter?
I've got a question about casbin-rs usage: I'm using it with actix-web and the [example states](https://github.com/actix/examples/blob/master/security/casbin/src/main.rs#L40) that the Enforcer should be wrapped in an RwLock. I wonder if this is because of the example using FileAdapter and that the protection by the RwLock can maybe be omitted when using a DB adapter like [sqlx-adapter](https://github.com/casbin-rs/sqlx-adapter)? Or does the RwLock protect state inside the single Enforcer instance? Thanks!

### PR DESCRIPTION
**Pull request by bk138**
Closes #278

### CODE REVIEW

**Comment by hsluoyz** [comment]
@hackerchai

**Review by PsiACE — APPROVED** [review]
LGTM

**Review by hackerchai — COMMENTED** [review]
lgtm

**Comment by hackerchai** [comment]
@bk138  please help to fix the clippy errors
https://github.com/casbin/casbin-rs/runs/4659375039?check_suite_focus=true

**Comment by PsiACE** [comment]
docs changes only, let's merge

**Comment by PsiACE** [comment]
> @bk138 please help to fix the clippy errors https://github.com/casbin/casbin-rs/runs/4659375039?check_suite_focus=true

see #281

**Pull request merged**
