### PR TITLE
Added Unit Tests for `addPolicies` and `removePolicies`

### LINKED ISSUE #65: Add unit tests for `addPolicies` and `removePolicies`
Following up from #55 need to add unit tests for the following apis:
```rust
async fn add_policies(&mut self, paramss: Vec<Vec<&str>>) -> Result<bool>;
async fn remove_policies(&mut self, paramss: Vec<Vec<&str>>) -> Result<bool>;
async fn add_named_policies(&mut self, ptype: &str, paramss: Vec<Vec<&str>>) -> Result<bool>;
async fn remove_named_policies(&mut self, ptype: &str, paramss: Vec<Vec<&str>>)
        -> Result<bool>;
async fn add_grouping_policies(&mut self, paramss: Vec<Vec<&str>>) -> Result<bool>;
async fn remove_grouping_policies(&mut self, paramss: Vec<Vec<&str>>) -> Result<bool>;
async fn add_named_grouping_policies(
        &mut self,
        ptype: &str,
        paramss: Vec<Vec<&str>>,
    ) -> Result<bool>;
async fn remove_named_grouping_policies(
        &mut self,
        ptype: &str,
        paramss: Vec<Vec<&str>>,
    ) -> Result<bool>;
async fn add_permissions_for_user(
        &mut self,
        user: &str,
        permissions: Vec<Vec<&str>>,
    ) -> Result<bool>;
async fn add_roles_for_user(
        &mut self,
        user: &str,
        roles: Vec<&str>,
        domain: Option<&str>,
    ) -> Result<bool>;
```

### PR DESCRIPTION
**Pull request by drholmie**
Fixes #65.
Added the following tests in `management_api.rs`:
- `test_modify_policies_api`
- `test_modify_grouping_policies_api`

For:
```rust
async fn add_policies(&mut self, paramss: Vec<Vec<&str>>) -> Result<bool>;
async fn remove_policies(&mut self, paramss: Vec<Vec<&str>>) -> Result<bool>;
async fn add_named_policies(&mut self, ptype: &str, paramss: Vec<Vec<&str>>) -> Result<bool>;
async fn remove_named_policies(&mut self, ptype: &str, paramss: Vec<Vec<&str>>)
        -> Result<bool>;
async fn add_grouping_policies(&mut self, paramss: Vec<Vec<&str>>) -> Result<bool>;
async fn remove_grouping_policies(&mut self, paramss: Vec<Vec<&str>>) -> Result<bool>;
async fn add_named_grouping_policies(
        &mut self,
        ptype: &str,
        paramss: Vec<Vec<&str>>,
    ) -> Result<bool>;
async fn remove_named_grouping_policies(
        &mut self,
        ptype: &str,
        paramss: Vec<Vec<&str>>,
    ) -> Result<bool>;
```

Modified the following tests in `rbac_api.rs`:
- `test_role_api`
- `test_permission_api`
- `test_role_api_threads`

For:
```rust
async fn add_permissions_for_user(
        &mut self,
        user: &str,
        permissions: Vec<Vec<&str>>,
    ) -> Result<bool>;
async fn add_roles_for_user(
        &mut self,
        user: &str,
        roles: Vec<&str>,
        domain: Option<&str>,
    ) -> Result<bool>;
```

### CODE REVIEW

**Comment by PsiACE** [comment]
Could you please format the code? It looks like the CI build failed.

**Comment by drholmie** [comment]
Thank you for pointing that out! Formatted the code.

**Comment by hsluoyz** [comment]
Please add `rust` after "```" to colorize your text block.

**Comment by GopherJ** [comment]
Hello @drholmie I believe there are many `unwrap` without `assert`, could you add them? Also thanks for your contributions.

**Comment by drholmie** [comment]
Ah! Thank you for pointing that out @GopherJ I believe you meant in the `management_api.rs` file? I'll begin adding those too.

**Comment by drholmie** [comment]
Added more `assert`, @GopherJ do let me know if more are required. Thank you again for going through the PR!

**Comment by GopherJ** [comment]
Thanks!

**Comment by drholmie** [comment]
Thanks for approving this and for all the help :)

**Pull request merged**
