### PR TITLE
using IndexSet to store policy in assertion

### PR DESCRIPTION
**Pull request by GopherJ**
Previously we are using `sort_unstable` + `dedup` to avoid adding a policy the second time, but the sort operation is expensive, so I made this PR which stores policies in `HashSet`, in rust there is no problem to compare two arrays.

That'll probably make it more efficient.

### CODE REVIEW

**Comment by GopherJ** [comment]
The disadvantage is that `HashSet` doesn't guarantee the order of elements, so when we run `get_policy` it will probably gives differents results:

1st run:
```
[["alice", "/user/profile", "read"], ["bob", "/user/profile", "write"]]
```
2nd run:
```
[["bob", "/user/profile", "write"], ["alice", "/user/profile", "read"]]
```

**Comment by GopherJ** [comment]
@hsluoyz  How do you think?

**Comment by hsluoyz** [comment]
@GopherJ will Golang Casbin keep the order?

**Comment by GopherJ** [comment]
@hsluoyz Yes it will keep the result's order. So I'm not sure how do we handle this, `sort_unstable + dedup` can solve the problem but it's really expensive operation:  nlogn + n probably.

**Comment by hsluoyz** [comment]
@GopherJ can we have the same behavior as Golang Casbin?

**Comment by GopherJ** [comment]
@hsluoyz Yes, I just changed `HashSet` to [IndexSet](https://docs.rs/indexmap/1.3.0/indexmap/set/struct.IndexSet.html#method.get) which guarantee the order.

**Comment by hsluoyz** [comment]
lgtm

**Pull request merged**
